In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [2]:
df = pd.read_csv("diabetes.csv")

In [3]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [4]:
df.shape

(768, 9)

In [5]:
df.size

6912

In [6]:
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [8]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [9]:
df1 = df[:650]
validation = df[650:]

In [10]:
df1.shape,validation.shape

((650, 9), (118, 9))

In [11]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 650 entries, 0 to 649
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               650 non-null    int64  
 1   Glucose                   650 non-null    int64  
 2   BloodPressure             650 non-null    int64  
 3   SkinThickness             650 non-null    int64  
 4   Insulin                   650 non-null    int64  
 5   BMI                       650 non-null    float64
 6   DiabetesPedigreeFunction  650 non-null    float64
 7   Age                       650 non-null    int64  
 8   Outcome                   650 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 45.8 KB


In [12]:
X = df1.drop("Outcome",axis=1)
Y = df1["Outcome"]

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, Y_train, Y_test = train_test_split(
     X, Y, test_size=0.2, random_state=101)

In [15]:
from sklearn.linear_model import LogisticRegression

In [16]:
log = LogisticRegression()

In [17]:
log.fit(X_train,Y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [29]:
log.coef_

array([[ 0.08372948,  0.03498865, -0.01653463, -0.00244267, -0.00185624,
         0.08056464,  1.48044061,  0.01818639]])

In [30]:
log.intercept_

array([-7.92069212])

In [18]:
prediction = log.predict(X_test)

In [19]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix,roc_auc_score

In [20]:
print(accuracy_score(Y_test,prediction))
print(roc_auc_score(Y_test,prediction))
print(confusion_matrix(Y_test,prediction))
print(classification_report(Y_test,prediction))

0.7769230769230769
0.7161172161172161
[[79 12]
 [17 22]]
              precision    recall  f1-score   support

           0       0.82      0.87      0.84        91
           1       0.65      0.56      0.60        39

    accuracy                           0.78       130
   macro avg       0.73      0.72      0.72       130
weighted avg       0.77      0.78      0.77       130



In [21]:
df["Outcome"].value_counts()

0    500
1    268
Name: Outcome, dtype: int64

In [22]:
#Validation

In [23]:
validation.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
650            1       91             54             25      100  25.2   
651            1      117             60             23      106  33.8   
652            5      123             74             40       77  34.1   
653            2      120             54              0        0  26.8   
654            1      106             70             28      135  34.2   

     DiabetesPedigreeFunction  Age  Outcome  
650                     0.234   23        0  
651                     0.466   27        0  
652                     0.269   28        0  
653                     0.455   27        0  
654                     0.142   22        0

In [24]:
validation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118 entries, 650 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               118 non-null    int64  
 1   Glucose                   118 non-null    int64  
 2   BloodPressure             118 non-null    int64  
 3   SkinThickness             118 non-null    int64  
 4   Insulin                   118 non-null    int64  
 5   BMI                       118 non-null    float64
 6   DiabetesPedigreeFunction  118 non-null    float64
 7   Age                       118 non-null    int64  
 8   Outcome                   118 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 8.4 KB


In [25]:
validation_Testx = validation.drop("Outcome",axis=1)
validation_y = validation["Outcome"]

In [26]:
predict_valid = log.predict(validation_Testx)

In [27]:
print(accuracy_score(validation_y,predict_valid))
print(roc_auc_score(validation_y,predict_valid))
print(confusion_matrix(validation_y,predict_valid))
print(classification_report(validation_y,predict_valid))

0.7796610169491526
0.7494672754946726
[[64  9]
 [17 28]]
              precision    recall  f1-score   support

           0       0.79      0.88      0.83        73
           1       0.76      0.62      0.68        45

    accuracy                           0.78       118
   macro avg       0.77      0.75      0.76       118
weighted avg       0.78      0.78      0.77       118

